# Generated by Django 5.1 on 2024-08-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=20)),
                ('Designation', models.TextField()),
                ('instagram', models.URLField()),
                ('github', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
